# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Thu Dec 24 17:36:07 2020
# ------------------------------------------------

package:
    name: poppler
    version: 20.12.1
source:
    patches:
        - cmakelists.win.patch
        - exportsymbols.patch
        - g-ir-scanner-libpath.patch
        - includesystembeforejpeg.patch
        - strncasecmp_fix.patch
        - vs2015-no-for-loop-constexpr.win.patch
        - windows-data.patch
    sha256: d0aa2586c0a4296c775f0d2045f28bb95a694113fc995f95350faa12930f7b35
    url: https://poppler.freedesktop.org/poppler-20.12.1.tar.xz
build:
    detect_binary_files_with_prefix: true
    number: '2'
    string: hd95df2c_2
requirements:
    build:
        - cmake 3.19.2 h39d44d4_0
        - m2-msys2-runtime 2.5.0.17080.65c939c 3
        - m2-patch 2.7.5 2
        - m2w64-gcc-libgfortran 5.3.0 6
        - m2w64-gcc-libs 5.3.0 7
        - m2w64-gcc-libs-core 5.3.0 7
        - m2w64-gmp 6.1.0 2
        - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
        - m2w64-pkg-config 0.29.1 2
        - make 4.3 h3d2af85_1
        - msys2-conda-epoch 20160418 1
        - ninja 1.10.2 h5362a0b_0
        - perl 5.26.2.1 h8ffe710_1008
        - vs2015_runtime 14.28.29325 h5e1d092_0
        - vs2017_win-64 19.16.27038 h2e3bad8_2
        - vswhere 2.7.1 h21ff451_0
    host:
        - ca-certificates 2020.12.5 h5b45459_0
        - cairo 1.16.0 hba8bd2f_1007
        - curl 7.71.1 h4b64cdc_8
        - freetype 2.10.4 h546665d_0
        - gettext 0.19.8.1 h1a89ca6_1005
        - glib 2.66.4 he2d232f_1
        - icu 68.1 h0e60522_0
        - jpeg 9d h8ffe710_0
        - krb5 1.17.2 hbae68bd_0
        - libcurl 7.71.1 h4b64cdc_8
        - libffi 3.3 h0e60522_2
        - libglib 2.66.4 h5320221_1
        - libiconv 1.16 he774522_0
        - libpng 1.6.37 h1d00b33_2
        - libssh2 1.9.0 hb06d900_5
        - libtiff 4.1.0 hc10be44_6
        - lz4-c 1.9.2 h62dcd97_2
        - openjpeg 2.3.1 h48faf41_3
        - openssl 1.1.1i h8ffe710_0
        - pcre 8.44 ha925a31_0
        - pixman 0.40.0 h8ffe710_0
        - python 3.9.1 h7840368_2_cpython
        - sqlite 3.34.0 h8ffe710_0
        - tk 8.6.10 h8ffe710_1
        - tzdata 2020d h516909a_0
        - vc 14.2 hb210afc_2
        - vs2015_runtime 14.28.29325 h5e1d092_0
        - xz 5.2.5 h62dcd97_1
        - zlib 1.2.11 h62dcd97_1010
        - zstd 1.4.5 h1f3a1b7_2
    run:
        - cairo >=1.16.0,<1.17.0a0
        - cairo >=1.16.0,<1.17.0a0
        - curl >=7.71.1,<8.0a0
        - freetype >=2.10.4,<3.0a0
        - freetype >=2.10.4,<3.0a0
        - glib
        - jpeg >=9d,<10a
        - jpeg >=9d,<10a
        - libglib >=2.66.4,<3.0a0
        - libpng >=1.6.37,<1.7.0a0
        - libpng >=1.6.37,<1.7.0a0
        - libtiff >=4.1.0,<5.0a0
        - libtiff >=4.1.0,<5.0a0
        - openjpeg >=2.3.1,<2.4.0a0
        - openjpeg >=2.3.1,<2.4.0a0
        - poppler-data
        - vc >=14.1,<15.0a0
        - vs2015_runtime >=14.16.27012
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - pdfinfo -listenc
        - pdfunite --help
        - pdftocairo --help
about:
    home: https://poppler.freedesktop.org/
    license: GPL-2.0-only
    license_family: GPL
    license_file: COPYING
    summary: The Poppler PDF manipulation library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pkgw
